name = "Blackjack"
uuid = "a97e59cd-db20-4c5a-8f1c-adab44fcc7fb"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
