name = "Blackjack"
uuid = "4c9388de-29bb-4495-884b-16087504c956"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
