name = "Blackjack"
uuid = "52cf9eef-b52f-41d0-92ef-9bef689243d0"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
