name = "BlackjackFacecards"
uuid = "30dc7974-6f84-477f-9dc5-0c44c588ea61"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "df6e7af7-d4ff-45dc-8d23-28f185ef5f73"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
