name = "BlackjackFacecards"
uuid = "1b45b8cd-5494-4195-b2f2-5f75f5073c35"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "d9ace13e-97da-48d3-8838-a9cb782d71f6"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
