name = "BlackjackFacecards"
uuid = "a31be507-ad6e-4d5c-8b4a-2dd8bcbe7623"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "f2f19ed5-ec21-47e7-8431-4bed6ff97b48"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
