name = "Blackjack"
uuid = "393725ba-b713-44fc-9c37-490fa1294a11"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
